kind = "mobile"
previewPath = "/mobile/"
title = "RentSaathi Mobile"
version = "1.0.0"
id = "artifacts/rent-tracker-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 24221

[services.development]
run = "pnpm --filter @workspace/rent-tracker-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rent-tracker-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/rent-tracker-mobile", "run", "serve" ]

[services.env]
PORT = "24221"
BASE_PATH = "/mobile/"
